packaging_format = 2

id = "processwire"
name = "ProcessWire"
description.en = "Friendly and powerful open source CMS with a strong API"
description.fr = "CMS open source convivial et puissant avec une API puissante"

version = "3.0.210~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MPL-2.0"
website = "https://processwire.com/"
userdoc = "https://processwire.com/docs/"
demo = "https://processwire.com/about/demo/"
code = "https://github.com/processwire/processwire"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/processwire"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/processwire/processwire/archive/refs/tags/3.0.210.zip"
        sha256 = "7436bae42fafafb7eff1476956ab54eaed3e0689ba2ecae5e4363033394c93f6"


    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-gd, php8.2-mysql"

    [resources.database]
    type = "mysql"
